openapi: 3.0.3
info:
  description: API đơn giản để quản lý sách trong thư viện.
  title: Library Management API
  version: 1.0.0
servers:
- url: http://localhost:5000
paths:
  /books:
    get:
      operationId: books_get
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: "#/components/schemas/Book"
                type: array
          description: Thành công
      summary: Lấy danh sách tất cả các cuốn sách
      x-openapi-router-controller: openapi_server.controllers.default_controller
    post:
      operationId: books_post
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/BookInput"
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: Đã tạo thành công
      summary: Thêm một cuốn sách mới
      x-openapi-router-controller: openapi_server.controllers.default_controller
  /books/{id}:
    get:
      operationId: books_id_get
      parameters:
      - explode: false
        in: path
        name: id
        required: true
        schema:
          type: string
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Book"
          description: Thành công
        "404":
          description: không tìm thấy sách
      summary: Lấy thông tin chi tiết của một cuốn sách
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas:
    Book:
      example:
        author: author
        isbn: isbn
        id: 046b6c7f-0b8a-43b9-b35d-6489e6daee91
        title: title
      properties:
        id:
          format: uuid
          title: id
          type: string
        title:
          title: title
          type: string
        author:
          title: author
          type: string
        isbn:
          title: isbn
          type: string
      required:
      - author
      - id
      - isbn
      - title
      title: Book
      type: object
    BookInput:
      example:
        author: author
        isbn: isbn
        title: title
      properties:
        title:
          title: title
          type: string
        author:
          title: author
          type: string
        isbn:
          title: isbn
          type: string
      required:
      - author
      - isbn
      - title
      title: BookInput
      type: object
