from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server.models.pet_type import PetType
from openapi_server import util

from openapi_server.models.pet_type import PetType  # noqa: E501

class Pet(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, name=None, age=None, kind=None):  # noqa: E501
        """Pet - a model defined in OpenAPI

        :param id: The id of this Pet.  # noqa: E501
        :type id: int
        :param name: The name of this Pet.  # noqa: E501
        :type name: str
        :param age: The age of this Pet.  # noqa: E501
        :type age: int
        :param kind: The kind of this Pet.  # noqa: E501
        :type kind: PetType
        """
        self.openapi_types = {
            'id': int,
            'name': str,
            'age': int,
            'kind': PetType
        }

        self.attribute_map = {
            'id': 'id',
            'name': 'name',
            'age': 'age',
            'kind': 'kind'
        }

        self._id = id
        self._name = name
        self._age = age
        self._kind = kind

    @classmethod
    def from_dict(cls, dikt) -> 'Pet':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Pet of this Pet.  # noqa: E501
        :rtype: Pet
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Pet.


        :return: The id of this Pet.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Pet.


        :param id: The id of this Pet.
        :type id: int
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self) -> str:
        """Gets the name of this Pet.


        :return: The name of this Pet.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Pet.


        :param name: The name of this Pet.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) < 1:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `1`")  # noqa: E501

        self._name = name

    @property
    def age(self) -> int:
        """Gets the age of this Pet.


        :return: The age of this Pet.
        :rtype: int
        """
        return self._age

    @age.setter
    def age(self, age: int):
        """Sets the age of this Pet.


        :param age: The age of this Pet.
        :type age: int
        """
        if age is None:
            raise ValueError("Invalid value for `age`, must not be `None`")  # noqa: E501
        if age is not None and age > 100:  # noqa: E501
            raise ValueError("Invalid value for `age`, must be a value less than or equal to `100`")  # noqa: E501
        if age is not None and age < 0:  # noqa: E501
            raise ValueError("Invalid value for `age`, must be a value greater than or equal to `0`")  # noqa: E501

        self._age = age

    @property
    def kind(self) -> PetType:
        """Gets the kind of this Pet.


        :return: The kind of this Pet.
        :rtype: PetType
        """
        return self._kind

    @kind.setter
    def kind(self, kind: PetType):
        """Sets the kind of this Pet.


        :param kind: The kind of this Pet.
        :type kind: PetType
        """
        if kind is None:
            raise ValueError("Invalid value for `kind`, must not be `None`")  # noqa: E501

        self._kind = kind
