from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class GETBooksId404Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, error=None):  # noqa: E501
        """GETBooksId404Response - a model defined in OpenAPI

        :param error: The error of this GETBooksId404Response.  # noqa: E501
        :type error: str
        """
        self.openapi_types = {
            'error': str
        }

        self.attribute_map = {
            'error': 'error'
        }

        self._error = error

    @classmethod
    def from_dict(cls, dikt) -> 'GETBooksId404Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The GET_books_id_404_response of this GETBooksId404Response.  # noqa: E501
        :rtype: GETBooksId404Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def error(self) -> str:
        """Gets the error of this GETBooksId404Response.


        :return: The error of this GETBooksId404Response.
        :rtype: str
        """
        return self._error

    @error.setter
    def error(self, error: str):
        """Sets the error of this GETBooksId404Response.


        :param error: The error of this GETBooksId404Response.
        :type error: str
        """
        if error is None:
            raise ValueError("Invalid value for `error`, must not be `None`")  # noqa: E501

        self._error = error
