from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ThMMTCuNSChMI201Response(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, id=None, title=None, author=None, isbn=None):  # noqa: E501
        """ThMMTCuNSChMI201Response - a model defined in OpenAPI

        :param id: The id of this ThMMTCuNSChMI201Response.  # noqa: E501
        :type id: str
        :param title: The title of this ThMMTCuNSChMI201Response.  # noqa: E501
        :type title: str
        :param author: The author of this ThMMTCuNSChMI201Response.  # noqa: E501
        :type author: str
        :param isbn: The isbn of this ThMMTCuNSChMI201Response.  # noqa: E501
        :type isbn: str
        """
        self.openapi_types = {
            'id': str,
            'title': str,
            'author': str,
            'isbn': str
        }

        self.attribute_map = {
            'id': 'id',
            'title': 'title',
            'author': 'author',
            'isbn': 'isbn'
        }

        self._id = id
        self._title = title
        self._author = author
        self._isbn = isbn

    @classmethod
    def from_dict(cls, dikt) -> 'ThMMTCuNSChMI201Response':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Th_m_m_t_cu_n_s_ch_m_i_201_response of this ThMMTCuNSChMI201Response.  # noqa: E501
        :rtype: ThMMTCuNSChMI201Response
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> str:
        """Gets the id of this ThMMTCuNSChMI201Response.


        :return: The id of this ThMMTCuNSChMI201Response.
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id: str):
        """Sets the id of this ThMMTCuNSChMI201Response.


        :param id: The id of this ThMMTCuNSChMI201Response.
        :type id: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def title(self) -> str:
        """Gets the title of this ThMMTCuNSChMI201Response.


        :return: The title of this ThMMTCuNSChMI201Response.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ThMMTCuNSChMI201Response.


        :param title: The title of this ThMMTCuNSChMI201Response.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this ThMMTCuNSChMI201Response.


        :return: The author of this ThMMTCuNSChMI201Response.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this ThMMTCuNSChMI201Response.


        :param author: The author of this ThMMTCuNSChMI201Response.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def isbn(self) -> str:
        """Gets the isbn of this ThMMTCuNSChMI201Response.


        :return: The isbn of this ThMMTCuNSChMI201Response.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this ThMMTCuNSChMI201Response.


        :param isbn: The isbn of this ThMMTCuNSChMI201Response.
        :type isbn: str
        """
        if isbn is None:
            raise ValueError("Invalid value for `isbn`, must not be `None`")  # noqa: E501

        self._isbn = isbn
