from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from openapi_server.models.base_model import Model
from openapi_server import util


class ThMMTCuNSChMIRequest(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, title=None, author=None, isbn=None):  # noqa: E501
        """ThMMTCuNSChMIRequest - a model defined in OpenAPI

        :param title: The title of this ThMMTCuNSChMIRequest.  # noqa: E501
        :type title: str
        :param author: The author of this ThMMTCuNSChMIRequest.  # noqa: E501
        :type author: str
        :param isbn: The isbn of this ThMMTCuNSChMIRequest.  # noqa: E501
        :type isbn: str
        """
        self.openapi_types = {
            'title': str,
            'author': str,
            'isbn': str
        }

        self.attribute_map = {
            'title': 'title',
            'author': 'author',
            'isbn': 'isbn'
        }

        self._title = title
        self._author = author
        self._isbn = isbn

    @classmethod
    def from_dict(cls, dikt) -> 'ThMMTCuNSChMIRequest':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Th_m_m_t_cu_n_s_ch_m_i_request of this ThMMTCuNSChMIRequest.  # noqa: E501
        :rtype: ThMMTCuNSChMIRequest
        """
        return util.deserialize_model(dikt, cls)

    @property
    def title(self) -> str:
        """Gets the title of this ThMMTCuNSChMIRequest.


        :return: The title of this ThMMTCuNSChMIRequest.
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title: str):
        """Sets the title of this ThMMTCuNSChMIRequest.


        :param title: The title of this ThMMTCuNSChMIRequest.
        :type title: str
        """
        if title is None:
            raise ValueError("Invalid value for `title`, must not be `None`")  # noqa: E501

        self._title = title

    @property
    def author(self) -> str:
        """Gets the author of this ThMMTCuNSChMIRequest.


        :return: The author of this ThMMTCuNSChMIRequest.
        :rtype: str
        """
        return self._author

    @author.setter
    def author(self, author: str):
        """Sets the author of this ThMMTCuNSChMIRequest.


        :param author: The author of this ThMMTCuNSChMIRequest.
        :type author: str
        """
        if author is None:
            raise ValueError("Invalid value for `author`, must not be `None`")  # noqa: E501

        self._author = author

    @property
    def isbn(self) -> str:
        """Gets the isbn of this ThMMTCuNSChMIRequest.


        :return: The isbn of this ThMMTCuNSChMIRequest.
        :rtype: str
        """
        return self._isbn

    @isbn.setter
    def isbn(self, isbn: str):
        """Sets the isbn of this ThMMTCuNSChMIRequest.


        :param isbn: The isbn of this ThMMTCuNSChMIRequest.
        :type isbn: str
        """
        if isbn is None:
            raise ValueError("Invalid value for `isbn`, must not be `None`")  # noqa: E501

        self._isbn = isbn
